joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

khau1_controller:
  type: effort_controllers/JointPositionController
  joint: khau1_link_joint
  pid: {p: 5.0, i: 0.005, d: 0.05}
  max_effort: 1.0  
  velocity_limit: 1 

khau2_controller:
  type: effort_controllers/JointPositionController
  joint: khau2_link_joint
  pid: {p: 5.0, i: 0.005, d: 0.05}
  max_effort: 1.0
  velocity_limit: 1

